### ISSUE TITLE
Remove the background image

### ISSUE THREAD

**Issue by ghost** [OpenFloodAI/openfloodai.github.io#1]
Remove the background image and edit the index.html to 
```
Welcome to OpenFloodAI
OpenFloodAI is an open-source community dedicated & focused on research & developing solutions for Flood related issues.
```

**Comment by nimitbhargava** [comment]
@adventuroussrv Can you add description of the issue to understand better?

**Comment by ghost** [comment]
Hi @nimitbhargava! I have updated the issue & added the description.

**Comment by nimitbhargava** [comment]
@adventuroussrv Can I pick up this issue?

**Comment by ghost** [comment]
sure go ahead! @nimitbhargava

**Comment by nimitbhargava** [comment]
@adventuroussrv Do you have some design in mind?

**Comment by ghost** [comment]
Any minimal design is fine we are just building a landing page for OpenFloodAI for now! I will open more issue soon!
