### ISSUE TITLE
add the slack link to Community section! 

### ISSUE THREAD

**Issue by ghost** [OpenFloodAI/openfloodai.github.io#15]
add the **slack link** to **Community** section! 
http://bit.ly/2mSDz5k

**Comment by BosEriko** [comment]
Hello! Can I take this one? :)

**Comment by ghost** [comment]
Hi @BosEriko go ahead!

**Comment by BosEriko** [comment]
@adventuroussrv hello. I couldn't find a community section. Just a menu link for the community. Is that what you meant? If so, I made a PR for that one. :)

**Comment by ghost** [comment]
> @adventuroussrv hello. I couldn't find a community section. Just a menu link for the community. Is that what you meant? If so, I made a PR for that one. :)

Hi @BosEriko if you visit https://openfloodai.github.io you will find it on upper-right corner!
Check out the code.

**Comment by Andy9822** [comment]
Hello, I didnt't refresh the page to see the other mate was also trying to solve this issue.
Btw I've submitted a PR to this issue [here](https://github.com/OpenFloodAI/openfloodai.github.io/pull/18)

**Comment by BhathiyaTK** [comment]
Hello @adventuroussrv! Can I contribute to this issue?

**Comment by ghost** [comment]
Hi Andy9822 We have already got the PR by @BosEriko as she responded first! 

Sure, @BhathiyaTK 
Please check out the latest issues! 
closing this..
