### ISSUE TITLE
Write a simple README for "How to Contribute to openfloodai.github.io"

### ISSUE THREAD

**Issue by ghost** [OpenFloodAI/openfloodai.github.io#22]
Write a simple README for "How to Contribute to openfloodai.github.io"

Add also the steps like
- Find an issue that you are interested to work on.
- Leave a comment that you are you would like to work!
- Fork the Project and add the feature or fixed the bug that mentioned on the issue!
-

**Comment by kshntn** [comment]
Hi @adventuroussrv I am interested in working on it!

**Comment by ghost** [comment]
Awesome! @kshntn Go ahead
