### ISSUE TITLE
Add card view design to About Navigation!

### ISSUE THREAD

**Issue by ghost** [OpenFloodAI/openfloodai.github.io#23]
Add card view design to **About** Navigation!

**// When About is clicked on navigation bar it should move to About Section** 

Add Two Card View Design and add the Two Project links as follows
- [openfloodai.github.io](https://github.com/OpenFloodAI/openfloodai.github.io)
- [OpenFloodAI-Android](https://github.com/OpenFloodAI/OpenFloodAI-Android)

Make a suitable design for the card view!
Home Page remains the same!

**Comment by NimishVerma** [comment]
Can I take this?

**Comment by ghost** [comment]
Awesome! Go ahead @bigpythonimish I have assigned you.

**Comment by im-ankitjais** [comment]
I want to work on #23 & #24 . Can I  ?

**Comment by ghost** [comment]
Sure @im-ankitjais You can make changes to it & make it look more awesome! and send us PR
