### ISSUE TITLE
add all the OpenFloodAI social links to Connect Navigation

### ISSUE THREAD

**Issue by ghost** [OpenFloodAI/openfloodai.github.io#24]
1.Create a section named as Connect 

**When Connect is clicked on navigation bar it should move to Connect Section** 

2.add social links to Connect section with Icons
// when the Icon is clicked it redirects to the link
eg. When the Twitter Icon is clicked it should redirect to OpenFloodAI Twitter handle!

**Twitter**: https://twitter.com/OpenFloodAI
**Facebook**: https://www.facebook.com/OpenFloodAI
**Linkedin**: https://www.linkedin.com/company/openfloodai
**Github**: https://github.com/OpenFloodAI

Website Design as follows:

             Home
              ↓ 
            About
              ↓
           Connect

**Comment by BhathiyaTK** [comment]
Can I take this?

**Comment by ghost** [comment]
Hi @BhathiyaTK Sure! Can you have a look at #23 too?

**Comment by ghost** [comment]
I have assigned you!

**Comment by BhathiyaTK** [comment]
@adventuroussrv Sure I will look at #23 too.

**Comment by BhathiyaTK** [comment]
PR done: #25
