### ISSUE TITLE
Move the Twitter feed Home to Connect!

### ISSUE THREAD

**Issue by ghost** [OpenFloodAI/openfloodai.github.io#33]
Move the Twitter feed  **Home** to **Connect**! 

The page is in three-part!

Design as follows:

         Home
          ↓ 
        About
          ↓
       Connect

**Comment by tanwanimohit** [comment]
![Screenshot (15)](https://user-images.githubusercontent.com/28397571/66072118-0d14a500-e572-11e9-9c78-f4a44c70f791.png)
![Screenshot (16)](https://user-images.githubusercontent.com/28397571/66072120-0dad3b80-e572-11e9-9b90-2eeff9a485fc.png)
Like this?

**Comment by ghost** [comment]
Yep! It will work can you please make it full screen for each part! 

@tanwanimohit

**Comment by tanwanimohit** [comment]
> Yep! It will work can you please make it full screen for each part!
> 
> @tanwanimohit

Can you elaborate a little please?

**Comment by ghost** [comment]
> > Yep! It will work can you please make it full screen for each part!
> > @tanwanimohit
> 
> Can you elaborate a little please?
@tanwanimohit
Here is an example like each part should have a full-screen scale!
![image](https://user-images.githubusercontent.com/31799654/66072816-692bf900-e573-11e9-8dac-b5dcbf319016.png)
