### ISSUE TITLE
> >make it full screen for each part!

### ISSUE THREAD

**Issue by ghost** [OpenFloodAI/openfloodai.github.io#36]
> > Yep! It will work can you please make it full screen for each part!
> > @tanwanimohit
> 
> Can you elaborate a little please?
@tanwanimohit
Here is an example like each part should have a full-screen scale!
![image](https://user-images.githubusercontent.com/31799654/66072816-692bf900-e573-11e9-8dac-b5dcbf319016.png)

_Originally posted by @adventuroussrv in https://github.com/OpenFloodAI/openfloodai.github.io/issues/33#issuecomment-537629488_

**Comment by BhathiyaTK** [comment]
@adventuroussrv Can I take this one?

**Comment by ghost** [comment]
Yeah! Sure @BhathiyaTK :)

**Comment by BhathiyaTK** [comment]
PR done: #37
