### ISSUE TITLE
Implement the design shared in the file!

### ISSUE THREAD

**Issue by ghost** [OpenFloodAI/openfloodai.github.io#42]
Implement the design shared in the file!

[page design.pdf](https://github.com/OpenFloodAI/openfloodai.github.io/files/3685672/page.design.pdf)

**Comment by Soniella** [comment]
I don't think it looks good though. The social media icons are generally added at the bottom on a line of their own in the footer.

**Comment by ghost** [comment]
That's a very good suggestion @Sonella! Can you please suggest any design!

**Comment by sonamkshenoy** [comment]
Yup, the social media icons could be put in one line of its own. Shall I send the PR to show what I mean?

**Comment by ghost** [comment]
Sure, @Soniella You can also add few more features and work on the design!
