### ISSUE TITLE
OpenFloodAI-Web design Suggestions!

### ISSUE THREAD

**Issue by ghost** [OpenFloodAI/openfloodai.github.io#44]
Hey folks! Share your valuable design suggestions for **OpenFloodAI-Web**

**Comment by muazhar** [comment]
Hey @adventuroussrv  Hope you are doing well, I think these Designs might interest you
![1](https://user-images.githubusercontent.com/48376727/66132169-181d1300-e60e-11e9-949e-80d5bac96d4a.jpg)
![2](https://user-images.githubusercontent.com/48376727/66132170-181d1300-e60e-11e9-834a-7bbf55e10276.png)
![3](https://user-images.githubusercontent.com/48376727/66132172-18b5a980-e60e-11e9-8690-558478a2210c.png)
![4](https://user-images.githubusercontent.com/48376727/66132173-18b5a980-e60e-11e9-8e25-52808828f4ac.jpg)
![5](https://user-images.githubusercontent.com/48376727/66132174-194e4000-e60e-11e9-9793-d52f61c14f2d.jpg)
<img width="888" alt="6" src="https://user-images.githubusercontent.com/48376727/66132176-194e4000-e60e-11e9-887f-571377640b28.png">

I hope you might find this valuable, if yes, would you like me to work on one of these. Thanks

**Comment by ghost** [comment]
Hi, @2016CS101UET Thanks for sharing the lovely designs!
We are looking for a design that will be suitable for **OpenFloodAI** & will be sticking to it for the development!

Stay in touch! Looking for more suggestions.

**Comment by ghost** [comment]
OpenFloodAI-Web design Suggestions!
