### ISSUE TITLE
add Typed.js 

### ISSUE THREAD

**Issue by ghost** [OpenFloodAI/openfloodai.github.io#54]
add Typed.js for this
```
Welcome to OpenFloodAI
OpenFloodAI is an open-source project dedicated & focused on research & developing
solutions for Flood related issues.
```

**Comment by abdus** [comment]
Let me do this.

**Comment by ghost** [comment]
Hi @thisisabdus sure!

**Comment by ghost** [comment]
if you wanna add any features let me know! I'm looking for it to make the page responsive!

**Comment by abdus** [comment]
Sure! For now, I am thinking of using typer.js instead of typed.js. Is that okay?

**Comment by ghost** [comment]
sure it will work! make sure it falls under any opensource license and add attribution if needed!! @thisisabdus
