### ISSUE TITLE
add the background images!

### ISSUE THREAD

**Issue by ghost** [OpenFloodAI/openfloodai.github.io#58]
add the background images! 

Here is the design idea! 
[design.pdf](https://github.com/OpenFloodAI/openfloodai.github.io/files/3728933/design.pdf)👈

[image1](https://pixabay.com/vectors/triangles-polygon-color-pink-1430105/)
[image2](https://pixabay.com/vectors/mesh-background-triangles-polygon-1430108/)

//Change the text color to white and make changes!
//for the project section change the card view to white or similar color that suits the design
//footer remains the same!

**Comment by ClaudioFuriniJr** [comment]
I'm on it! Can you assign to me, please?

**Comment by ghost** [comment]
Sure! @ClaudioFuriniJr 
I have assigned you!

**Comment by RamanaVem** [comment]
Hey @adventuroussrv i have a good idea some how on this, can i take a look on this?

**Comment by ClaudioFuriniJr** [comment]
@adventuroussrv Did a first version based on the .pdf
Let me know if it is ok for you :)

Thank you

**Comment by RamanaVem** [comment]
Hey @adventuroussrv i have done something can i get access to push, if it's fine.

**Comment by ghost** [comment]
Hi @ClaudioFuriniJr It's fine for now! I will open more issue! You may still work on it and make PR

**Comment by ghost** [comment]
Hi @RamanaVem Sure make a PR to [dev](https://github.com/OpenFloodAI/openfloodai.github.io/tree/dev) branch!!


This issue was already assigned to @ClaudioFuriniJr 
you may check out any new issue if you wanna work on!!

**Comment by ghost** [comment]
I will open more issues soon! closing this for now
