### ISSUE TITLE
fix the mobile view! make it responsive

### ISSUE THREAD

**Issue by ghost** [OpenFloodAI/openfloodai.github.io#60]
# Fix the mobile view! make it responsive
![mobile](https://user-images.githubusercontent.com/31799654/66842322-abe4cc80-ef88-11e9-8bbb-274ca85ba439.jpg)

**Comment by GregSithole** [comment]
Hey, I can work on this! Can you assign me to it!

**Comment by ghost** [comment]
Hi, @GregSithole go ahead! 
please add the screenshots for different views when you make PR!

**Comment by RajkumarMittal** [comment]
Hey, may i also contribute in this? @adventuroussrv

**Comment by RajkumarMittal** [comment]
i can make some good changes

**Comment by GregSithole** [comment]
@adventuroussrv Cool, I've made a pull request. If you're not happy with it or want more changes, please do let me know!

@RajkumarMittal Sorry, I was already assigned to it, but should they want more changes to the Nav hopefully, you'll be tagged to it

**Comment by ghost** [comment]
Hi @RajkumarMittal sure 
you may look for a new issue or add any feature to the website! also you can work the code and make it faster!
