### ISSUE TITLE
add a new card view

### ISSUE THREAD

**Issue by ghost** [OpenFloodAI/openfloodai.github.io#72]
add [Climate-Change-Datasets](https://github.com/OpenFloodAI/Climate-Change-Datasets)
under projects the same as other cards!

**Comment by Shivam2498** [comment]
Please assign me this issue @adventuroussrv

**Comment by ghost** [comment]
Hi @Shivam2498 go ahead!

**Comment by Shivam2498** [comment]
Raised a PR 
Please review
