### ISSUE TITLE
create sections for the OpenFloodAI website!

### ISSUE THREAD

**Issue by ghost** [OpenFloodAI/openfloodai.github.io#8]
We are building an one-page website!

//create a section on upper left-corner name it as **OpenFloodAI**
//create a 5 section on upper right-corner
**Home**   **About**   [**Contribute**](https://github.com/OpenFloodAI)   **Connect**  **Community**[slack-logo]

**Comment by randydaniel** [comment]
Wanted to contribute, but has this been assigned to @emrizkiem already?

**Comment by ghost** [comment]
Hi @randydaniel Sure, Please check out the latest issue!
