### ISSUE TITLE
add social links to Connect section!

### ISSUE THREAD

**Issue by ghost** [OpenFloodAI/openfloodai.github.io#9]
add social links to **Connect** section

**Twitter**: https://twitter.com/OpenFloodAI
**Facebook**: https://www.facebook.com/OpenFloodAI
**Github**: https://github.com/OpenFloodAI

**Comment by emrizkiem** [comment]
I would like to work on this issue. Could you assign me for this issue?

**Comment by ghost** [comment]
Sure! @emrizkiem can you please check out the #8

**Comment by emrizkiem** [comment]
Right!

**Comment by ghost** [comment]
> Right!

Hi @emrizkiem If you wanna work on that issue[ #8 ] I can assign you for that!

**Comment by emrizkiem** [comment]
> > Right!
> 
> Hi @emrizkiem If you wanna work on that issue[ #8 ] I can assign you for that!

yes i want to overcome that problem

**Comment by ghost** [comment]
Awesome! go ahead

**Comment by adventuroussrv** [comment]
**add Linkedin link to the page**! https://www.linkedin.com/company/openfloodai
